// Code generated by protoc-gen-go.
// source: msgs.proto
// DO NOT EDIT!

/*
Package rtnm_pb is a generated protocol buffer package.

It is generated from these files:
	msgs.proto

It has these top-level messages:
	MSGS
	ProbeRegister
	MasterRegConfirm
*/
package rtnm_pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MSGS struct {
	PReg             *ProbeRegister    `protobuf:"bytes,1,opt" json:"PReg,omitempty"`
	RConf            *MasterRegConfirm `protobuf:"bytes,2,opt" json:"RConf,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MSGS) Reset()         { *m = MSGS{} }
func (m *MSGS) String() string { return proto.CompactTextString(m) }
func (*MSGS) ProtoMessage()    {}

func (m *MSGS) GetPReg() *ProbeRegister {
	if m != nil {
		return m.PReg
	}
	return nil
}

func (m *MSGS) GetRConf() *MasterRegConfirm {
	if m != nil {
		return m.RConf
	}
	return nil
}

type ProbeRegister struct {
	ProbeIp          *string `protobuf:"bytes,1,opt" json:"ProbeIp,omitempty"`
	ProbeLocation    *string `protobuf:"bytes,2,opt" json:"ProbeLocation,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProbeRegister) Reset()         { *m = ProbeRegister{} }
func (m *ProbeRegister) String() string { return proto.CompactTextString(m) }
func (*ProbeRegister) ProtoMessage()    {}

func (m *ProbeRegister) GetProbeIp() string {
	if m != nil && m.ProbeIp != nil {
		return *m.ProbeIp
	}
	return ""
}

func (m *ProbeRegister) GetProbeLocation() string {
	if m != nil && m.ProbeLocation != nil {
		return *m.ProbeLocation
	}
	return ""
}

type MasterRegConfirm struct {
	ProbeKA          *uint32 `protobuf:"varint,1,opt" json:"ProbeKA,omitempty"`
	TestsList        *string `protobuf:"bytes,2,opt" json:"TestsList,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MasterRegConfirm) Reset()         { *m = MasterRegConfirm{} }
func (m *MasterRegConfirm) String() string { return proto.CompactTextString(m) }
func (*MasterRegConfirm) ProtoMessage()    {}

func (m *MasterRegConfirm) GetProbeKA() uint32 {
	if m != nil && m.ProbeKA != nil {
		return *m.ProbeKA
	}
	return 0
}

func (m *MasterRegConfirm) GetTestsList() string {
	if m != nil && m.TestsList != nil {
		return *m.TestsList
	}
	return ""
}

func init() {
}
